# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, address: str=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param address: The address of this Address.  # noqa: E501
        :type address: str
        """
        self.swagger_types = {
            'address': str
        }

        self.attribute_map = {
            'address': 'address'
        }
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address(self) -> str:
        """Gets the address of this Address.


        :return: The address of this Address.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this Address.


        :param address: The address of this Address.
        :type address: str
        """

        self._address = address
